wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.10
    cli_version: 0.16.0
    framework: huggingface
    huggingface_version: 4.47.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1738828140.459333
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      - 98
      - 105
      3:
      - 13
      - 23
      4: 3.11.10
      5: 0.16.0
      6: 4.47.0
      8:
      - 5
      13: linux-x86_64
