wandb_version: 1

name:
  desc: null
  value: backtrack_countdown
train_type:
  desc: null
  value: sft
seed:
  desc: null
  value: 42
output_dir:
  desc: null
  value: ../output_countdown/
num_train:
  desc: null
  value: 500000
context_length:
  desc: null
  value: 128
eval_steps:
  desc: null
  value: 5000
log_steps:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 16
gradient_accumulation_steps:
  desc: null
  value: 1
num_train_epochs:
  desc: null
  value: 3
weight_decay:
  desc: null
  value: 0.01
warmup_steps:
  desc: null
  value: 1
lr_scheduler_type:
  desc: null
  value: cosine
lr:
  desc: null
  value: 1.0e-05
save_total_limit:
  desc: null
  value: 0
save_steps:
  desc: null
  value: 5000
_wandb:
  desc: null
  value:
    python_version: 3.11.10
    cli_version: 0.16.0
    framework: huggingface
    huggingface_version: 4.47.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1738827836.021805
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      - 98
      - 105
      2:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      - 98
      - 105
      3:
      - 13
      - 16
      - 23
      4: 3.11.10
      5: 0.16.0
      6: 4.47.0
      8:
      - 5
      13: linux-x86_64
